# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
    dist: trusty
  - osx
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
julia:
  - 1.0
  - nightly
before-install:
  "alias pip=pip3"
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
