name = "DFOLS"
uuid = "d38edb08-f825-11e8-02cc-c338a489feff"
authors = ["Arnav Sood <soodarnav01@gmail.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
